LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY FF_tipoT IS
	PORT(T, CLK : IN STD_LOGIC;
	Q1 : BUFFER STD_LOGIC;    
	Q2 : BUFFER STD_LOGIC;   
	Q3 : BUFFER STD_LOGIC;
	Q4 : BUFFER STD_LOGIC     ); 
END FF_tipoT;

ARCHITECTURE a OF FF_tipoT IS

BEGIN
	PROCESS(CLK)
	BEGIN
		IF (CLK'EVENT) THEN 
			Q1 <= ;

		END IF;
	END PROCESS;
END a;